name: 'startify-styles'
description: 'Development environment for website creation with design and static coding.'
publish_to: 'none'
version: 1.5.0
environment:
  sdk: '>=2.10.0 <3.0.0'
dev_dependencies:
  sass: '^1.50.0'
  source_maps: '^0.10.10'